//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeatherDashboard.Web.Localizations {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SharedResource {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResource() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("WeatherDashboard.Web.Localizations.SharedResource", typeof(SharedResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string DewPoint {
            get {
                return ResourceManager.GetString("DewPoint", resourceCulture);
            }
        }
        
        internal static string Humidity {
            get {
                return ResourceManager.GetString("Humidity", resourceCulture);
            }
        }
        
        internal static string Pressure {
            get {
                return ResourceManager.GetString("Pressure", resourceCulture);
            }
        }
        
        internal static string Sunrise {
            get {
                return ResourceManager.GetString("Sunrise", resourceCulture);
            }
        }
        
        internal static string Sunset {
            get {
                return ResourceManager.GetString("Sunset", resourceCulture);
            }
        }
        
        internal static string UVIndex {
            get {
                return ResourceManager.GetString("UVIndex", resourceCulture);
            }
        }
        
        internal static string Visibility {
            get {
                return ResourceManager.GetString("Visibility", resourceCulture);
            }
        }
        
        internal static string Wind {
            get {
                return ResourceManager.GetString("Wind", resourceCulture);
            }
        }
        
        internal static string WindStatus {
            get {
                return ResourceManager.GetString("WindStatus", resourceCulture);
            }
        }
        
        internal static string WeatherCode_ClearSky {
            get {
                return ResourceManager.GetString("WeatherCode_ClearSky", resourceCulture);
            }
        }
        
        internal static string WeatherCode_MainlyClear {
            get {
                return ResourceManager.GetString("WeatherCode_MainlyClear", resourceCulture);
            }
        }
        
        internal static string WeatherCode_PartlyCloudy {
            get {
                return ResourceManager.GetString("WeatherCode_PartlyCloudy", resourceCulture);
            }
        }
        
        internal static string WeatherCode_Overcast {
            get {
                return ResourceManager.GetString("WeatherCode_Overcast", resourceCulture);
            }
        }
        
        internal static string WeatherCode_Fog {
            get {
                return ResourceManager.GetString("WeatherCode_Fog", resourceCulture);
            }
        }
        
        internal static string WeatherCode_DepositingRimeFog {
            get {
                return ResourceManager.GetString("WeatherCode_DepositingRimeFog", resourceCulture);
            }
        }
        
        internal static string WeatherCode_DrizzleLight {
            get {
                return ResourceManager.GetString("WeatherCode_DrizzleLight", resourceCulture);
            }
        }
        
        internal static string WeatherCode_DrizzleModerate {
            get {
                return ResourceManager.GetString("WeatherCode_DrizzleModerate", resourceCulture);
            }
        }
        
        internal static string WeatherCode_DrizzleDense {
            get {
                return ResourceManager.GetString("WeatherCode_DrizzleDense", resourceCulture);
            }
        }
        
        internal static string WeatherCode_FreezingDrizzleLight {
            get {
                return ResourceManager.GetString("WeatherCode_FreezingDrizzleLight", resourceCulture);
            }
        }
        
        internal static string WeatherCode_FreezingDrizzleDense {
            get {
                return ResourceManager.GetString("WeatherCode_FreezingDrizzleDense", resourceCulture);
            }
        }
        
        internal static string WeatherCode_RainSlight {
            get {
                return ResourceManager.GetString("WeatherCode_RainSlight", resourceCulture);
            }
        }
        
        internal static string WeatherCode_RainModerate {
            get {
                return ResourceManager.GetString("WeatherCode_RainModerate", resourceCulture);
            }
        }
        
        internal static string WeatherCode_RainHeavy {
            get {
                return ResourceManager.GetString("WeatherCode_RainHeavy", resourceCulture);
            }
        }
        
        internal static string WeatherCode_FreezingRainLight {
            get {
                return ResourceManager.GetString("WeatherCode_FreezingRainLight", resourceCulture);
            }
        }
        
        internal static string WeatherCode_FreezingRainHeavy {
            get {
                return ResourceManager.GetString("WeatherCode_FreezingRainHeavy", resourceCulture);
            }
        }
        
        internal static string WeatherCode_SnowFallSlight {
            get {
                return ResourceManager.GetString("WeatherCode_SnowFallSlight", resourceCulture);
            }
        }
        
        internal static string WeatherCode_SnowFallModerate {
            get {
                return ResourceManager.GetString("WeatherCode_SnowFallModerate", resourceCulture);
            }
        }
        
        internal static string WeatherCode_SnowFallHeavy {
            get {
                return ResourceManager.GetString("WeatherCode_SnowFallHeavy", resourceCulture);
            }
        }
        
        internal static string WeatherCode_SnowGrains {
            get {
                return ResourceManager.GetString("WeatherCode_SnowGrains", resourceCulture);
            }
        }
        
        internal static string WeatherCode_RainShowersSlight {
            get {
                return ResourceManager.GetString("WeatherCode_RainShowersSlight", resourceCulture);
            }
        }
        
        internal static string WeatherCode_RainShowersModerate {
            get {
                return ResourceManager.GetString("WeatherCode_RainShowersModerate", resourceCulture);
            }
        }
        
        internal static string WeatherCode_RainShowersViolent {
            get {
                return ResourceManager.GetString("WeatherCode_RainShowersViolent", resourceCulture);
            }
        }
        
        internal static string WeatherCode_SnowShowersSlight {
            get {
                return ResourceManager.GetString("WeatherCode_SnowShowersSlight", resourceCulture);
            }
        }
        
        internal static string WeatherCode_SnowShowersHeavy {
            get {
                return ResourceManager.GetString("WeatherCode_SnowShowersHeavy", resourceCulture);
            }
        }
        
        internal static string WeatherCode_ThunderstormSlightOrModerate {
            get {
                return ResourceManager.GetString("WeatherCode_ThunderstormSlightOrModerate", resourceCulture);
            }
        }
        
        internal static string WeatherCode_ThunderstormWithHail {
            get {
                return ResourceManager.GetString("WeatherCode_ThunderstormWithHail", resourceCulture);
            }
        }
        
        internal static string WeatherCode_ThunderstormWithSevereHail {
            get {
                return ResourceManager.GetString("WeatherCode_ThunderstormWithSevereHail", resourceCulture);
            }
        }
        
        internal static string Weather_Humidity_VeryLow {
            get {
                return ResourceManager.GetString("Weather_Humidity_VeryLow", resourceCulture);
            }
        }
        
        internal static string Weather_Humidity_Low {
            get {
                return ResourceManager.GetString("Weather_Humidity_Low", resourceCulture);
            }
        }
        
        internal static string Weather_Humidity_Comfortable {
            get {
                return ResourceManager.GetString("Weather_Humidity_Comfortable", resourceCulture);
            }
        }
        
        internal static string Weather_UvIndex_Moderate {
            get {
                return ResourceManager.GetString("Weather_UvIndex_Moderate", resourceCulture);
            }
        }
        
        internal static string Weather_Humidity_High {
            get {
                return ResourceManager.GetString("Weather_Humidity_High", resourceCulture);
            }
        }
        
        internal static string Weather_Humidity_VeryHigh {
            get {
                return ResourceManager.GetString("Weather_Humidity_VeryHigh", resourceCulture);
            }
        }
        
        internal static string Weather_UvIndex_Low {
            get {
                return ResourceManager.GetString("Weather_UvIndex_Low", resourceCulture);
            }
        }
        
        internal static string Weather_Humidity_Moderate {
            get {
                return ResourceManager.GetString("Weather_Humidity_Moderate", resourceCulture);
            }
        }
        
        internal static string Weather_UvIndex_High {
            get {
                return ResourceManager.GetString("Weather_UvIndex_High", resourceCulture);
            }
        }
        
        internal static string Weather_UvIndex_VeryHigh {
            get {
                return ResourceManager.GetString("Weather_UvIndex_VeryHigh", resourceCulture);
            }
        }
        
        internal static string Weather_UvIndex_Extreme {
            get {
                return ResourceManager.GetString("Weather_UvIndex_Extreme", resourceCulture);
            }
        }
    }
}
